= Knative Sample Event Source

A Spring Boot Application that generates Cloud Events using the `cloud-event-publisher` component.

NOTE: the link:../README.adoc#prerequisites[prerequisites] for running this sample.



== Build

Build and push the docker image to GCR. Provide your GCP project as a property.

```
cd ../cloud-events-sample-source
./mvnw clean package jib:build -Dgcp.project=<your_GCP_project>
```

== Run

You can run the app standalone, by default it generates and publishes Cloud Events to an internal endpoint `http://localhost:8080/events`.

```
docker run -it gcr.io/<your_GCP_project>/sample-event-source:latest
```

=== Running on PFS

This is a variation of the documented samples that send events the `message dumper` service, e.g., https://github.com/knative/eventing-sources/blob/master/samples/gcp-pubsub-source/README.md[gcp-pubsub-source].

This example creates an eventing source that generates a "Hello World" message every second.
The source publishes to a channel which the `message dumper` subscribes to.
The `message dumper` logs the contents of each message it receives.


NOTE: The PFS install includes Knative Eventing, and In memory ClusterChannelProvisioner out of the box, so you can skip these steps.

First, create a Channel:

```
kubectl apply -f config/channel-qux1.yaml
```
Next, subscribe the `message dumper` to the qux-1 channel.

```
kubectl apply -f config/subscriber-message-dumper.yaml
```

Edit `config/containersource-sample-event-source.yaml` and change the repository to the GCR repository where you published the eventing source image.
```
kubectl apply -f config/containersource-sample-event-source.yaml
```

Soon, tou should see the eventing source and message dumper pods running in the default namespace, e.g.,
```
$kubectl get pods

NAME                                                  READY   STATUS    RESTARTS   AGE
pod/cloud-event-source-xzczd-5fb879c79d-vst2q         2/2     Running   0          2m
pod/message-dumper-00001-deployment-f5f5494cf-87tf6   3/3     Running   0          2m
```

The logs from the eventing source should show a message like this every second:

```
$kubectl logs -f cloud-event-source-xzczd-5fb879c79d-vst2q source

2018-12-19 16:42:12.543  INFO 1 --- [     parallel-1] o.d.c.s.CloudEventsSourceApplication     : Posting cloud event DefaultCloudEventImpl{specversion='0.2', type='test.event.type', source=/test/source, id='cbc0c9e4-2643-45c1-8ff3-6f4e33b963a5', time=2018-12-19T16:42:12.543Z[GMT], schemaURL=null, contentType='text/plain', data=Hello World} to http://qux-1-channel.default.svc.cluster.local/
2018-12-19 16:42:12.552  INFO 1 --- [or-http-epoll-1] o.d.c.s.CloudEventsSourceApplication     : status 202 ACCEPTED
```

And the message dumper logs:

```
$kubectl logs -f message-dumper-00001-deployment-f5f5494cf-87tf6 user-container

2018/12/19 16:48:31 Message Dumper received a message: POST / HTTP/1.1
Host: message-dumper.default.svc.cluster.local
Accept-Encoding: gzip
Content-Length: 401
Content-Type: application/cloudevents+json
User-Agent: Go-http-client/1.1
X-B3-Parentspanid: 2899ed709288c149
X-B3-Sampled: 1
X-B3-Spanid: ef4ce73bc46204ab
X-B3-Traceid: 2899ed709288c149
X-Forwarded-For: 127.0.0.1
X-Forwarded-Proto: http
X-Request-Id: b8834396-b106-9333-8475-a96d98ebb135

{"type":"test.event.type","source":"/test/source","id":"007d5b72-dc2d-4756-846c-6dc2e0797049","time":1545238111.543000000,"schemaURL":null,"contentType":"text/plain","data":{"type":"test.event.type","source":"/test/source","id":"d3b9d668-9261-4033-9ca1-cc6f83c00d45","time":1545238111.543000000,"schemaURL":null,"contentType":"text/plain","data":"Hello World","specVersion":"0.2"},"specVersion":"0.2"}
```

Terminate the event source, after a few minutes, the message dumper will terminate away since it is no longer receiving messages.
```
kubectl delete containersource.sources.eventing.knative.dev/cloud-event-source
```

