= Cloud Events Publisher

This repository contains a `cloud-events-publisher` library along with some samples for integrating with https://github.com/knative/docs/blob/master/eventing/README.md[Knative Eventing]

The core link:cloud-events-publisher[cloud-events-publisher] provides Spring Boot auto configuration for a `CloudEventsPublisher` component, which publishes https://cloudevents.io/[Cloud Events] via http.

The `cloud-events-publisher` is configured by the following properties:

* *cloudevents.publisher.target-uri* - The URI of a service consuming Cloud Events
* *cloudevents.publisher.timeout-ms* - Request time out in MS.
* *io.cloudevents.event.type* - A String identifier
* *io.cloudevents.event.source* - A URI identifier
* *io.cloudevents.event.content-type* - The content-type of the event data

== Knative Eventing Sources

This repo includes some examples of https://github.com/knative/eventing-sources[Knative Eventing Sources] based on the https://github.com/knative/eventing-sources/blob/master/samples/sources_v1alpha1_containersources.yaml[ContainerSource Eventing Source].

* link:cloud-events-sample-source/README.adoc[cloud-events-sample-source]

