= SCDF Knative Interoperability

This repository contains the following core libraries along with some samples for integrating with https://github.com/knative/docs/blob/master/eventing/README.md[Knative Eventing]

* link:source-supplier-adapter[source-supplier-adapter] a library to adapt a Spring Cloud Stream `Source` component to a `Supplier<Flux<Message<?>>>`
* link:cloud-event-publisher[cloud-event-publisher] a library to publish Cloud Events via HTTP.

== Sample Knative Eventing Sources

This repo includes some examples of https://github.com/knative/eventing-sources[Knative Eventing Sources] based on the https://github.com/knative/docs/tree/master/eventing#containersource[ContainerSource Eventing Source].

* link:cloud-events-sample-source[cloud-events-sample-source]
* link:time-source-knative[time-source-knative]

[prerequisites]
== Prerequisites

* These instructions pertain to for https://docs.pivotal.io/pfs/index.html[PFS] https://docs.pivotal.io/pfs/install-on-pks.html[installed on PKS] running on Google Cloud Platform (GCP)
* Docker CLI with GCR credentials configured
* Install the core libraries in your local Maven repo.

```
cd scdf-knative-interoperability
./mvnw clean install
```
=== To use the riff/PFS CLI to create channels and subscriptions
NOTE: The `riff` and `pfs` CLIs are interchangeable.
An earlier version of the CLI is initially available on the PFS download page which is not compatible with the current eventing model used to create eventing sources.
Binaries of current versions have restricted access, but you can https://github.com/projectriff/riff/blob/master/README.adoc[manually build] the `riff` CLI, if necessary.

* pfs CLI 0.2 or higher or riff CLI 0.3 or higher

Alternatively, use `kubectl apply` with the provided config. You can use `pfs function create` with either version.


