apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: kafka-external-service
spec:
  hosts:
  - kafka.default.svc.cluster.local
  ports:
  - number: 9092
    name: tcp
    protocol: TCP
  location: MESH_EXTERNAL
  resolution: STATIC

