# Subscription from the GcpPubSubSource's output Channel to the Knative Service below.

apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: log
  namespace: default
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: time-channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: log

